[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
monitor_rts = 0
monitor_dtr = 0
upload_speed = 460800
upload_port = COM17

lib_deps = 
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.2

; DMT touchscreen pins for ESP32-C3
build_flags = 
    -DDMT_TX_PIN=21
    -DDMT_RX_PIN=20
    -DCORE_DEBUG_LEVEL=5
    -DBOARD_HAS_PSRAM=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_SERIAL_EVENT_TASK_RUNNING_CORE=-1
